### ISSUE TITLE
Exception "HTTP 415 Unsupported Media Type"

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/RADAR-Commons-Android#7]
Just a heads up, 703114d36bc42aebb40a731f5fb1a772904a6910 introduced this exception for me:
```
...W/KafkaConnectionChecker: Sender is disconnected
    java.io.IOException: Failed to submit (HTTP status code 415): {"error_code":415,"message":"HTTP 415 Unsupported Media Type"}
        at org.radarcns.producer.rest.RestSender$RestTopicSender.send(RestSender.java:226)
        at org.radarcns.android.kafka.KafkaDataSubmitter.doImmediateSend(KafkaDataSubmitter.java:414)
        at org.radarcns.android.kafka.KafkaDataSubmitter.access$1100(KafkaDataSubmitter.java:56)
        at org.radarcns.android.kafka.KafkaDataSubmitter$6.run(KafkaDataSubmitter.java:396)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at org.radarcns.android.util.AndroidThreadFactory$1.run(AndroidThreadFactory.java:43)
        at java.lang.Thread.run(Thread.java:818)
```
Prevents sending any data to the REST.
Does not throw if I revert the commit.

**Comment by sboettcher** [comment]
Probably also fixed by https://github.com/RADAR-CNS/RADAR-Commons/commit/0b1733593063c05fcbd6a5af89eb045fcf3da06c, see https://github.com/RADAR-CNS/RADAR-Commons/issues/15
